using System;
using System.Linq;

namespace Advent_of_Code
{
    class Level_7
    {
        static void Main_7(string[] args)
        {
            string[] operations = {"clear maroon bag contain 1 dull lavender bag",
"wavy turquoise bag contain 4 vibrant magenta bag, 4 light violet bag, 5 bright gold bag, 2 faded black bag",
"wavy beige bag contain 3 plaid magenta bag, 3 wavy lime bag, 2 clear turquoise bag, 3 muted cyan bag",
"mirrored black bag contain 1 plaid red bag, 3 light gold bag, 3 wavy violet bag",
"vibrant fuchsia bag contain 2 dark lime bag, 2 mirrored black bag, 2 light magenta bag, 2 drab chartreuse bag",
"vibrant plum bag contain 4 dim cyan bag, 3 pale maroon bag",
"dark tan bag contain 3 faded white bag, 3 wavy tan bag, 4 pale indigo bag",
"faded green bag contain 2 dim cyan bag, 5 dim magenta bag, 2 wavy maroon bag, 2 faded white bag",
"clear black bag contain 4 striped green bag, 2 dim violet bag, 1 dull tan bag",
"light olive bag contain 5 striped indigo bag, 3 dim coral bag, 1 drab bronze bag, 3 mirrored beige bag",
"dim black bag contain 1 faded tan bag, 5 shiny crimson bag",
"striped fuchsia bag contain 3 dim cyan bag",
"pale plum bag contain 1 light lavender bag, 3 dim aqua bag, 1 shiny blue bag, 5 dark orange bag",
"wavy crimson bag contain 2 pale crimson bag, 1 muted teal bag, 2 drab olive bag, 4 faded green bag",
"mirrored aqua bag contain 4 shiny red bag, 4 light maroon bag, 4 light violet bag, 5 clear salmon bag",
"light orange bag contain 4 dim crimson bag, 3 dim red bag, 3 mirrored orange bag",
"shiny bronze bag contain 3 mirrored violet bag, 1 dull blue bag",
"vibrant red bag contain 1 drab beige bag",
"light violet bag contain 4 dim cyan bag",
"dotted aqua bag contain 1 dotted crimson bag, 3 dark red bag, 4 dark fuchsia bag",
"drab teal bag contain 2 mirrored violet bag, 2 mirrored beige bag, 2 shiny crimson bag",
"clear coral bag contain 5 striped fuchsia bag, 2 shiny indigo bag",
"dim gray bag contain 4 plaid salmon bag, 4 faded purple bag, 4 dull violet bag, 3 clear coral bag",
"dotted cyan bag contain 1 shiny turquoise bag",
"dim red bag contain 2 wavy magenta bag, 2 faded maroon bag, 5 striped fuchsia bag",
"dull magenta bag contain 4 clear teal bag",
"vibrant coral bag contain 3 pale indigo bag, 5 wavy red bag, 1 clear lime bag, 1 bright red bag",
"striped silver bag contain 3 posh chartreuse bag",
"posh coral bag contain 1 mirrored orange bag, 2 plaid lavender bag",
"dull brown bag contain 1 light salmon bag",
"dotted bronze bag contain 2 clear teal bag, 2 muted orange bag, 3 dark cyan bag, 2 muted maroon bag",
"posh red bag contain 2 posh gray bag, 1 wavy blue bag",
"faded violet bag contain 4 light purple bag",
"faded red bag contain 3 drab brown bag",
"mirrored tomato bag contain 5 muted maroon bag, 1 wavy lavender bag",
"vibrant beige bag contain 4 muted maroon bag, 2 plaid violet bag, 1 dim cyan bag",
"shiny turquoise bag contain 2 faded turquoise bag, 1 bright olive bag, 1 striped aqua bag, 2 mirrored blue bag",
"plaid black bag contain 1 shiny teal bag",
"dull fuchsia bag contain 3 posh tan bag, 4 dotted coral bag",
"wavy tomato bag contain 3 light lavender bag",
"posh salmon bag contain 5 plaid chartreuse bag",
"striped green bag contain 3 dim cyan bag, 1 dark cyan bag, 3 shiny coral bag",
"dim brown bag contain 4 dotted tan bag, 2 dark white bag, 1 plaid coral bag",
"wavy plum bag contain 5 muted crimson bag",
"striped turquoise bag contain 2 bright plum bag, 1 muted salmon bag, 2 vibrant white bag, 3 pale coral bag",
"posh white bag contain 5 mirrored plum bag, 1 drab lavender bag, 4 drab brown bag",
"wavy purple bag contain 4 striped fuchsia bag, 4 shiny indigo bag, 1 wavy violet bag",
"muted coral bag contain 1 vibrant plum bag, 4 plaid salmon bag, 2 bright indigo bag",
"light salmon bag contain 5 wavy olive bag, 2 dull violet bag, 3 vibrant orange bag",
"light indigo bag contain 3 mirrored fuchsia bag",
"drab white bag contain 1 pale green bag, 1 shiny teal bag, 4 bright yellow bag",
"vibrant teal bag contain 4 drab turquoise bag, 3 shiny coral bag, 4 posh tan bag",
"muted yellow bag contain 2 faded lavender bag",
"pale silver bag contain 4 dotted green bag",
"faded gold bag contain 1 faded orange bag, 2 drab chartreuse bag",
"mirrored teal bag contain 2 dim tan bag, 2 plaid violet bag, 4 pale brown bag",
"muted chartreuse bag contain 4 shiny yellow bag, 1 posh beige bag",
"clear yellow bag contain 3 faded maroon bag, 5 striped blue bag, 3 dull silver bag, 5 striped gold bag",
"vibrant black bag contain 2 dull green bag, 3 vibrant white bag, 1 mirrored gold bag",
"striped indigo bag contain 1 vibrant orange bag, 3 striped black bag, 2 pale aqua bag, 3 light crimson bag",
"posh lime bag contain 1 clear lime bag, 1 pale aqua bag, 3 plaid white bag",
"drab silver bag contain 3 wavy aqua bag, 2 plaid yellow bag, 1 posh black bag, 2 plaid beige bag",
"mirrored chartreuse bag contain 1 drab teal bag, 5 posh maroon bag",
"faded brown bag contain 5 mirrored blue bag, 2 pale aqua bag, 3 dim black bag",
"vibrant orange bag contain 3 bright tan bag, 5 shiny teal bag, 4 dotted crimson bag, 2 posh cyan bag",
"drab blue bag contain 4 dark aqua bag",
"plaid beige bag contain 2 plaid salmon bag, 4 dull maroon bag",
"faded white bag contain 1 dim aqua bag",
"bright lime bag contain 3 drab gray bag, 1 striped lime bag",
"dim maroon bag contain 1 dotted salmon bag",
"clear fuchsia bag contain 2 pale plum bag",
"plaid violet bag contain 3 light magenta bag, 1 bright indigo bag, 1 pale tan bag",
"drab maroon bag contain 4 light gray bag, 1 striped orange bag, 5 drab salmon bag",
"light turquoise bag contain 4 plaid red bag, 5 drab plum bag",
"pale magenta bag contain 3 wavy red bag, 2 muted orange bag",
"striped plum bag contain 3 dark violet bag, 5 striped aqua bag, 1 posh chartreuse bag",
"muted silver bag contain 1 striped lavender bag, 4 dotted salmon bag",
"dark olive bag contain 1 mirrored cyan bag, 4 dull tan bag",
"dotted brown bag contain 4 bright lavender bag",
"bright salmon bag contain 4 drab blue bag",
"clear orange bag contain 1 posh cyan bag",
"clear tomato bag contain 1 clear red bag, 2 shiny yellow bag",
"wavy black bag contain 1 mirrored bronze bag",
"vibrant gold bag contain 2 posh olive bag, 4 shiny red bag",
"muted tomato bag contain 5 dotted indigo bag, 2 dark magenta bag, 1 faded indigo bag, 1 shiny indigo bag",
"dim tan bag contain 2 drab brown bag",
"posh purple bag contain 4 light violet bag, 5 drab chartreuse bag, 4 striped fuchsia bag",
"drab turquoise bag contain 3 bright indigo bag",
"clear gold bag contain 2 wavy magenta bag, 1 bright olive bag",
"dim crimson bag contain 2 drab gold bag, 1 dull tomato bag, 1 posh indigo bag",
"dark lime bag contain 5 wavy magenta bag, 3 mirrored fuchsia bag, 5 dotted chartreuse bag, 1 dull bronze bag",
"posh orange bag contain 2 mirrored aqua bag, 1 shiny green bag, 5 plaid teal bag",
"dotted chartreuse bag contain 3 wavy violet bag, 5 pale white bag, 1 posh violet bag, 2 dark aqua bag",
"wavy green bag contain 3 dim olive bag, 4 light lavender bag, 3 light olive bag",
"dark beige bag contain 4 shiny orange bag",
"dark orange bag contain 5 clear orange bag",
"vibrant white bag contain 2 dotted purple bag, 4 dark fuchsia bag, 3 dull bronze bag",
"shiny fuchsia bag contain 2 shiny gold bag",
"plaid teal bag contain 4 light maroon bag",
"faded beige bag contain 4 dark aqua bag, 4 mirrored black bag, 1 vibrant orange bag",
"wavy lime bag contain 4 dull cyan bag, 1 striped aqua bag, 2 plaid brown bag, 5 vibrant teal bag",
"wavy silver bag contain 3 drab lime bag",
"posh lavender bag contain 1 dotted purple bag",
"dark crimson bag contain 3 posh green bag, 3 dark green bag",
"dull teal bag contain 5 plaid salmon bag",
"clear brown bag contain 5 mirrored purple bag, 5 vibrant orange bag",
"striped white bag contain 3 dull maroon bag",
"clear violet bag contain 4 bright red bag, 1 dark orange bag, 3 dull maroon bag, 3 muted maroon bag",
"faded magenta bag contain 1 shiny yellow bag",
"dim beige bag contain 5 striped salmon bag",
"dull white bag contain 1 shiny tan bag",
"posh crimson bag contain 1 mirrored green bag, 4 dark orange bag",
"light teal bag contain 5 bright tan bag, 5 light indigo bag",
"wavy orange bag contain 2 pale maroon bag, 2 clear maroon bag",
"light lime bag contain 3 dim silver bag, 1 dim purple bag, 1 striped cyan bag",
"muted gray bag contain 2 light green bag, 4 dark aqua bag, 4 plaid coral bag, 2 mirrored lime bag",
"bright fuchsia bag contain 1 striped crimson bag, 5 faded purple bag, 2 plaid violet bag, 2 vibrant magenta bag",
"light chartreuse bag contain 4 bright bronze bag, 3 wavy teal bag, 5 muted tan bag, 4 light bronze bag",
"plaid gold bag contain 5 wavy teal bag, 4 clear magenta bag",
"dull silver bag contain 5 dim aqua bag, 3 muted silver bag, 3 mirrored blue bag, 4 clear orange bag",
"shiny maroon bag contain 3 dark olive bag, 3 muted turquoise bag",
"faded turquoise bag contain 1 light gold bag, 3 pale fuchsia bag, 4 shiny silver bag",
"posh indigo bag contain 4 muted salmon bag, 2 pale green bag",
"dotted violet bag contain 4 shiny lime bag, 4 muted violet bag, 1 muted yellow bag, 4 shiny red bag",
"faded salmon bag contain 5 muted lime bag",
"dotted white bag contain 5 dotted indigo bag, 3 wavy brown bag, 5 pale aqua bag",
"dark brown bag contain 5 wavy maroon bag, 3 plaid beige bag, 5 drab white bag",
"shiny white bag contain 1 dotted bronze bag, 5 dull black bag, 3 muted white bag, 4 wavy maroon bag",
"bright chartreuse bag contain 1 striped green bag",
"plaid indigo bag contain 4 dull bronze bag",
"bright violet bag contain 1 shiny yellow bag",
"pale maroon bag contain 3 striped fuchsia bag, 5 plaid silver bag, 4 shiny teal bag",
"shiny plum bag contain 4 wavy plum bag, 5 faded tomato bag",
"wavy tan bag contain 3 dim black bag, 4 posh black bag",
"plaid lavender bag contain 4 dull tan bag, 2 vibrant beige bag",
"faded aqua bag contain 1 dull lavender bag, 4 vibrant orange bag, 4 posh black bag",
"faded lavender bag contain 1 shiny coral bag, 1 plaid black bag, 1 wavy bronze bag, 5 dark coral bag",
"shiny indigo bag contain 4 dotted green bag",
"dark bronze bag contain 5 faded crimson bag, 3 dim lavender bag, 2 wavy white bag",
"muted olive bag contain 5 light yellow bag, 1 dull chartreuse bag, 4 dim lime bag",
"wavy olive bag contain 3 dotted orange bag",
"vibrant purple bag contain 3 faded maroon bag, 1 clear bronze bag, 5 striped black bag, 5 muted indigo bag",
"striped coral bag contain 1 mirrored black bag",
"dull violet bag contain 1 dotted purple bag",
"dim blue bag contain 1 shiny indigo bag, 5 striped cyan bag",
"drab aqua bag contain 5 clear chartreuse bag",
"striped bronze bag contain 5 wavy lavender bag, 5 shiny silver bag, 2 posh crimson bag",
"striped orange bag contain 1 muted salmon bag",
"clear white bag contain 2 dark coral bag, 1 plaid silver bag, 2 drab gold bag, 4 dark red bag",
"dotted tan bag contain 4 mirrored silver bag",
"striped crimson bag contain 2 dim olive bag, 3 dotted purple bag",
"muted bronze bag contain 5 dotted gray bag",
"striped tomato bag contain 4 mirrored aqua bag",
"drab tan bag contain 1 dotted white bag, 3 dotted coral bag, 5 muted olive bag",
"light maroon bag contain 1 dim olive bag",
"dark blue bag contain 1 mirrored maroon bag, 1 shiny salmon bag, 3 dull cyan bag",
"vibrant maroon bag contain 5 dull fuchsia bag",
"bright gray bag contain 1 wavy red bag",
"posh brown bag contain 2 dim beige bag, 2 shiny teal bag",
"striped blue bag contain 1 dotted chartreuse bag, 2 clear violet bag, 1 drab teal bag",
"dim indigo bag contain 3 clear purple bag",
"striped teal bag contain 2 dotted teal bag",
"plaid orange bag contain 5 dim black bag, 2 wavy bronze bag, 4 drab bronze bag, 2 shiny salmon bag",
"pale salmon bag contain 2 dotted plum bag",
"vibrant aqua bag contain 2 wavy orange bag",
"faded coral bag contain 5 dark fuchsia bag, 3 vibrant orange bag, 4 posh lavender bag, 5 dotted purple bag",
"bright tomato bag contain 3 plaid plum bag, 5 faded maroon bag, 4 bright green bag",
"wavy gray bag contain 5 pale silver bag, 2 clear cyan bag, 1 dim yellow bag, 1 clear aqua bag",
"dark aqua bag contain 1 pale maroon bag, 1 dotted gray bag, 2 muted plum bag, 4 muted orange bag",
"plaid maroon bag contain 4 muted plum bag, 1 plaid beige bag, 4 bright indigo bag, 5 vibrant orange bag",
"light gray bag contain 1 faded crimson bag",
"shiny silver bag contain 4 striped cyan bag, 4 mirrored fuchsia bag, 2 plaid salmon bag",
"plaid blue bag contain 2 dim olive bag, 2 posh purple bag, 1 dotted bronze bag, 2 shiny fuchsia bag",
"shiny olive bag contain 1 posh indigo bag",
"dotted plum bag contain 4 shiny coral bag, 2 drab beige bag, 3 dim gray bag",
"pale beige bag contain 4 drab orange bag",
"muted white bag contain 1 faded orange bag, 2 mirrored red bag, 3 wavy fuchsia bag, 2 drab blue bag",
"dark gold bag contain 1 mirrored beige bag, 3 plaid violet bag, 2 dotted bronze bag, 1 wavy bronze bag",
"clear cyan bag contain 1 striped fuchsia bag, 4 dotted lime bag, 3 drab olive bag, 3 dull blue bag",
"bright black bag contain 2 posh lavender bag, 3 wavy brown bag",
"bright olive bag contain 4 dark chartreuse bag, 3 plaid salmon bag, 2 muted orange bag, 5 pale aqua bag",
"light silver bag contain 3 plaid maroon bag",
"drab indigo bag contain 1 muted cyan bag, 1 clear magenta bag, 1 dark brown bag",
"dull gold bag contain 2 posh beige bag, 1 vibrant magenta bag",
"muted purple bag contain 2 dark salmon bag, 4 faded brown bag, 5 faded black bag",
"pale violet bag contain 2 dull bronze bag, 3 dull aqua bag",
"dark green bag contain 3 mirrored white bag, 2 striped cyan bag, 4 muted chartreuse bag, 2 faded white bag",
"dark indigo bag contain 4 dotted green bag, 4 dotted cyan bag, 5 bright bronze bag, 5 faded bronze bag",
"posh plum bag contain 1 light crimson bag",
"dark yellow bag contain 1 faded purple bag, 2 muted olive bag",
"bright crimson bag contain 2 striped tan bag",
"dim plum bag contain 2 bright silver bag, 1 shiny beige bag, 2 posh teal bag",
"dull blue bag contain 1 faded purple bag",
"drab violet bag contain 1 dim white bag, 4 vibrant lavender bag, 3 dull magenta bag",
"mirrored yellow bag contain 3 wavy lavender bag",
"clear plum bag contain 3 vibrant cyan bag, 4 plaid chartreuse bag, 5 light violet bag",
"dim coral bag contain 3 mirrored red bag, 1 pale maroon bag, 3 dark chartreuse bag",
"striped purple bag contain 1 mirrored tomato bag, 4 dotted green bag",
"wavy magenta bag contain 4 mirrored bronze bag, 5 bright fuchsia bag, 3 mirrored violet bag, 3 drab aqua bag",
"faded crimson bag contain 5 posh black bag",
"dotted maroon bag contain 1 muted salmon bag, 5 striped salmon bag",
"dark violet bag contain 1 plaid black bag, 3 dim gray bag, 3 bright lavender bag",
"bright lavender bag contain 4 mirrored blue bag, 2 mirrored black bag, 3 wavy red bag",
"light white bag contain 1 striped salmon bag, 3 plaid white bag, 5 clear lime bag, 5 dim aqua bag",
"wavy lavender bag contain 2 dull tan bag",
"vibrant violet bag contain 1 drab olive bag, 2 faded indigo bag, 2 posh black bag",
"bright silver bag contain 5 posh black bag, 3 posh lavender bag, 4 clear lime bag, 2 dim aqua bag",
"muted cyan bag contain 2 clear red bag, 2 plaid black bag",
"dull coral bag contain 5 dotted tan bag",
"dull purple bag contain 1 dotted lavender bag",
"muted gold bag contain 4 dim aqua bag",
"wavy maroon bag contain 4 light aqua bag, 5 bright black bag, 3 dull black bag",
"posh violet bag contain 2 dark chartreuse bag, 3 striped fuchsia bag",
"dull olive bag contain 1 dark chartreuse bag, 1 plaid tomato bag, 5 muted coral bag, 5 light gold bag",
"shiny coral bag contain 5 dull violet bag, 3 bright tan bag, 3 muted orange bag, 3 shiny indigo bag",
"dotted green bag contain 4 wavy bronze bag, 3 dull violet bag, 2 striped beige bag",
"dull tan bag contain 2 light maroon bag, 5 posh tan bag, 4 pale tan bag",
"mirrored gold bag contain 4 wavy lime bag",
"faded lime bag contain 5 dotted salmon bag, 1 plaid brown bag, 5 posh tan bag",
"plaid tan bag contain 5 drab plum bag, 2 dotted salmon bag",
"shiny cyan bag contain 2 dark coral bag, 4 posh yellow bag, 5 dotted brown bag, 5 dull maroon bag",
"posh aqua bag contain 2 light bronze bag, 4 light green bag",
"clear crimson bag contain 1 faded crimson bag, 2 posh tan bag, 2 dotted orange bag",
"drab black bag contain 2 dull tomato bag, 4 muted red bag, 4 dotted turquoise bag, 1 mirrored red bag",
"vibrant blue bag contain 2 posh coral bag, 3 wavy teal bag",
"light gold bag contain 5 posh gray bag, 5 shiny brown bag, 3 dark coral bag",
"wavy teal bag contain 5 bright tan bag, 5 clear coral bag",
"clear blue bag contain 1 striped green bag, 3 mirrored green bag",
"dark tomato bag contain 4 wavy yellow bag, 4 striped magenta bag, 1 wavy bronze bag, 1 dotted salmon bag",
"dull black bag contain 2 posh lavender bag, 5 pale aqua bag",
"mirrored crimson bag contain 4 dim turquoise bag, 2 mirrored aqua bag, 1 drab tan bag",
"dark chartreuse bag contain 1 dotted green bag",
"shiny salmon bag contain 5 light yellow bag, 4 pale fuchsia bag, 5 muted olive bag",
"light magenta bag contain 1 clear teal bag",
"dim orange bag contain 3 dark plum bag",
"striped black bag contain 5 shiny coral bag, 2 dull violet bag, 3 drab olive bag, 1 mirrored red bag",
"dotted gold bag contain 3 pale indigo bag, 2 wavy salmon bag, 1 light plum bag",
"shiny chartreuse bag contain 2 plaid green bag",
"light cyan bag contain 3 posh chartreuse bag, 5 striped lime bag, 4 wavy red bag",
"posh chartreuse bag contain 2 wavy violet bag",
"plaid fuchsia bag contain 4 mirrored blue bag, 5 pale tan bag",
"muted black bag contain 2 striped lime bag, 2 light olive bag, 2 plaid tan bag, 2 light lavender bag",
"striped aqua bag contain 5 mirrored red bag",
"shiny lime bag contain 2 faded white bag, 4 clear silver bag, 1 wavy fuchsia bag, 5 plaid lavender bag",
"drab magenta bag contain 5 dim purple bag, 2 dim silver bag, 3 clear brown bag, 4 wavy turquoise bag",
"mirrored silver bag contain 5 mirrored cyan bag, 5 dull silver bag, 5 drab violet bag",
"striped cyan bag contain 5 bright indigo bag",
"wavy violet bag contain 2 dim cyan bag, 2 plaid silver bag",
"pale teal bag contain 1 light maroon bag, 1 clear lime bag, 4 dark turquoise bag",
"wavy fuchsia bag contain 3 drab plum bag, 1 dotted white bag",
"muted green bag contain 5 bright orange bag",
"light yellow bag contain 4 shiny bronze bag, 4 wavy white bag, 3 drab turquoise bag",
"plaid purple bag contain 5 dotted purple bag, 3 plaid magenta bag, 1 wavy magenta bag",
"posh bronze bag contain 1 vibrant coral bag",
"vibrant green bag contain 3 plaid orange bag, 1 posh fuchsia bag, 1 faded brown bag",
"dim yellow bag contain 4 shiny gold bag, 5 mirrored magenta bag",
"drab lavender bag contain 3 muted coral bag, 5 drab aqua bag",
"dull chartreuse bag contain 1 vibrant white bag",
"plaid bronze bag contain 4 posh indigo bag",
"mirrored brown bag contain 2 wavy violet bag, 1 shiny crimson bag",
"clear silver bag contain 5 dim green bag, 2 vibrant gray bag, 3 pale white bag",
"drab salmon bag contain 5 shiny teal bag, 2 plaid teal bag, 4 striped magenta bag",
"dotted tomato bag contain 4 shiny tan bag, 3 dotted bronze bag, 4 clear lime bag",
"light tan bag contain 4 dotted silver bag, 1 mirrored violet bag, 3 dim lime bag",
"shiny tan bag contain 4 dotted gray bag, 5 striped cyan bag, 2 dull violet bag, 5 pale maroon bag",
"pale tomato bag contain 4 bright orange bag, 2 posh chartreuse bag",
"faded silver bag contain 4 dark turquoise bag, 4 faded gray bag, 5 wavy bronze bag",
"plaid gray bag contain 1 bright red bag",
"pale olive bag contain 3 posh beige bag, 4 faded coral bag",
"plaid yellow bag contain 5 dim blue bag, 1 drab plum bag, 1 dark coral bag, 2 faded purple bag",
"dim green bag contain 1 muted orange bag",
"wavy cyan bag contain 4 clear brown bag, 5 vibrant tan bag",
"clear teal bag contain 4 dark chartreuse bag",
"vibrant bronze bag contain 2 dim cyan bag, 4 shiny lime bag",
"muted salmon bag contain 4 clear coral bag, 2 posh lavender bag, 2 pale aqua bag",
"shiny gray bag contain 5 drab blue bag, 2 dull chartreuse bag, 5 wavy bronze bag, 2 dull salmon bag",
"muted blue bag contain 4 faded black bag, 3 dim lavender bag, 5 light violet bag, 2 mirrored maroon bag",
"dotted blue bag contain 4 light bronze bag",
"dark teal bag contain 4 dim lavender bag, 4 shiny gray bag, 4 wavy salmon bag, 2 pale white bag",
"light purple bag contain 1 clear salmon bag, 1 plaid brown bag",
"light tomato bag contain 4 striped lavender bag, 1 muted bronze bag",
"muted lime bag contain 4 mirrored olive bag, 1 dark aqua bag",
"pale bronze bag contain 1 mirrored brown bag",
"dotted black bag contain 4 vibrant magenta bag",
"shiny brown bag contain 2 bright tan bag",
"faded cyan bag contain 4 dotted lavender bag, 2 vibrant fuchsia bag, 3 light green bag",
"drab cyan bag contain 5 shiny lime bag",
"faded tan bag contain 5 shiny silver bag",
"dim fuchsia bag contain 5 dim orange bag, 3 mirrored fuchsia bag",
"drab fuchsia bag contain 4 plaid silver bag",
"striped beige bag contain no other bag",
"muted fuchsia bag contain 1 plaid silver bag, 5 shiny silver bag, 3 dark orange bag, 5 posh silver bag",
"bright beige bag contain 2 light crimson bag, 4 posh violet bag, 5 dotted purple bag",
"muted crimson bag contain 2 wavy salmon bag, 1 clear tomato bag, 1 pale bronze bag",
"drab olive bag contain 1 dull violet bag, 5 dotted crimson bag, 1 bright gold bag, 4 muted orange bag",
"dotted silver bag contain 2 dim indigo bag, 2 clear gray bag",
"pale blue bag contain 3 dotted teal bag, 5 muted tomato bag, 1 clear tan bag",
"dark fuchsia bag contain 2 dark plum bag, 5 posh tan bag",
"dull plum bag contain 3 pale green bag",
"faded indigo bag contain 4 plaid white bag",
"posh teal bag contain 5 drab maroon bag, 4 striped purple bag, 4 clear tan bag",
"light beige bag contain 1 dull orange bag",
"pale turquoise bag contain 1 bright olive bag, 5 drab tomato bag, 5 faded turquoise bag, 1 mirrored brown bag",
"shiny orange bag contain 4 plaid silver bag, 2 wavy brown bag, 5 clear teal bag",
"pale lavender bag contain 4 light plum bag",
"clear olive bag contain 2 wavy fuchsia bag, 4 dim black bag",
"faded blue bag contain 5 pale white bag, 5 plaid tomato bag, 3 muted orange bag, 5 clear red bag",
"dotted salmon bag contain 5 light gold bag, 1 muted green bag, 3 light black bag, 1 mirrored green bag",
"vibrant yellow bag contain 1 clear purple bag, 5 dotted coral bag",
"light blue bag contain 4 dark tan bag, 1 mirrored aqua bag, 5 clear lime bag, 5 drab coral bag",
"bright blue bag contain 4 dim maroon bag",
"mirrored orange bag contain 4 dotted plum bag, 2 dotted yellow bag, 4 dull cyan bag, 2 shiny tan bag",
"dotted teal bag contain 3 light crimson bag, 1 mirrored black bag, 3 wavy olive bag",
"wavy chartreuse bag contain 5 drab bronze bag, 1 muted salmon bag",
"striped brown bag contain 1 vibrant violet bag, 3 dull plum bag, 1 faded brown bag",
"plaid aqua bag contain 4 striped black bag, 5 muted white bag",
"dark purple bag contain 3 mirrored orange bag, 5 wavy lavender bag",
"mirrored tan bag contain 4 wavy indigo bag",
"posh silver bag contain 3 striped magenta bag, 1 dark chartreuse bag, 5 dotted white bag, 4 wavy tan bag",
"faded yellow bag contain 4 plaid magenta bag",
"bright brown bag contain 4 drab tomato bag",
"mirrored turquoise bag contain 5 plaid purple bag, 1 mirrored red bag, 4 striped green bag",
"plaid green bag contain 2 drab chartreuse bag",
"dotted olive bag contain 2 dull white bag",
"shiny teal bag contain no other bag",
"shiny red bag contain 5 striped cyan bag",
"dotted orange bag contain 2 clear teal bag, 5 striped cyan bag",
"shiny violet bag contain 5 posh violet bag",
"bright indigo bag contain no other bag",
"plaid white bag contain 2 bright indigo bag",
"drab plum bag contain no other bag",
"clear gray bag contain 1 mirrored gold bag, 1 dark beige bag, 2 drab silver bag, 4 striped green bag",
"dim magenta bag contain 1 posh cyan bag",
"dull cyan bag contain 5 pale fuchsia bag, 4 plaid fuchsia bag, 4 clear orange bag, 1 dark gold bag",
"light brown bag contain 1 dull violet bag",
"dotted fuchsia bag contain 3 striped crimson bag, 3 dim lime bag",
"dark magenta bag contain 5 dark plum bag, 3 mirrored fuchsia bag",
"dull tomato bag contain 2 shiny orange bag, 2 dark fuchsia bag",
"dull crimson bag contain 2 muted turquoise bag",
"mirrored salmon bag contain 4 mirrored bronze bag, 1 clear white bag, 3 dark red bag, 3 dim olive bag",
"shiny aqua bag contain 3 shiny green bag, 1 light lavender bag, 3 drab salmon bag, 1 dark tan bag",
"bright plum bag contain 4 dull lavender bag, 4 muted maroon bag, 2 bright coral bag, 4 dull maroon bag",
"dark red bag contain 1 bright olive bag",
"pale crimson bag contain 3 dotted green bag, 2 plaid tomato bag",
"dim bronze bag contain 4 plaid cyan bag",
"vibrant indigo bag contain 1 dark blue bag, 5 dotted orange bag",
"mirrored lavender bag contain 4 dark cyan bag, 1 shiny green bag, 1 mirrored gold bag, 1 shiny silver bag",
"bright magenta bag contain 2 faded indigo bag, 5 pale aqua bag, 4 dark magenta bag",
"drab orange bag contain 3 dull turquoise bag, 1 light magenta bag",
"vibrant salmon bag contain 3 striped blue bag, 3 vibrant teal bag",
"drab beige bag contain 1 drab plum bag, 2 wavy violet bag, 3 mirrored brown bag",
"muted beige bag contain 2 wavy tan bag, 5 wavy red bag",
"bright aqua bag contain 1 dark fuchsia bag, 5 dull black bag, 2 plaid red bag, 2 bright blue bag",
"shiny tomato bag contain 4 faded brown bag",
"dim lavender bag contain 2 dotted purple bag",
"posh fuchsia bag contain 5 plaid crimson bag, 3 dark orange bag, 1 vibrant red bag",
"muted brown bag contain 5 posh cyan bag, 4 wavy tan bag",
"light crimson bag contain 1 shiny red bag",
"wavy coral bag contain 5 muted magenta bag, 1 dull silver bag, 4 faded olive bag",
"mirrored bronze bag contain 1 bright lavender bag, 5 muted indigo bag, 1 wavy olive bag",
"wavy salmon bag contain 4 dotted bronze bag, 3 drab plum bag",
"vibrant brown bag contain 1 posh coral bag, 2 posh green bag, 3 faded olive bag",
"dim cyan bag contain no other bag",
"dull lavender bag contain 5 striped cyan bag, 5 dim cyan bag",
"pale orange bag contain 3 vibrant tan bag",
"drab chartreuse bag contain 4 wavy teal bag, 3 plaid black bag, 1 dim blue bag",
"drab gray bag contain 1 pale chartreuse bag",
"dim lime bag contain 3 clear teal bag, 4 posh chartreuse bag, 3 bright black bag, 5 muted red bag",
"plaid cyan bag contain 3 wavy purple bag",
"dotted lime bag contain 5 bright olive bag, 3 vibrant violet bag, 4 bright tomato bag, 3 dark magenta bag",
"dark lavender bag contain 5 light silver bag, 3 striped brown bag",
"dotted coral bag contain 2 dotted green bag, 2 wavy brown bag",
"bright orange bag contain 2 dull black bag, 5 posh purple bag, 2 muted indigo bag, 5 shiny gold bag",
"wavy white bag contain 3 plaid salmon bag, 1 muted plum bag, 3 plaid indigo bag, 3 dull aqua bag",
"dark white bag contain 5 mirrored teal bag, 3 dark lime bag",
"vibrant magenta bag contain 2 mirrored fuchsia bag, 1 clear lime bag",
"light plum bag contain 4 dull aqua bag",
"pale indigo bag contain 1 dotted coral bag, 5 drab beige bag, 3 dim green bag",
"dull yellow bag contain 3 dotted silver bag",
"dim white bag contain 3 clear chartreuse bag, 1 clear tomato bag",
"bright maroon bag contain 2 dark bronze bag",
"dotted crimson bag contain 2 plaid silver bag, 5 drab plum bag",
"dull turquoise bag contain 3 faded coral bag",
"mirrored maroon bag contain 5 shiny fuchsia bag",
"posh beige bag contain 4 plaid aqua bag, 3 muted red bag",
"shiny lavender bag contain 5 striped brown bag, 4 bright red bag",
"drab purple bag contain 1 posh plum bag, 3 pale salmon bag, 5 striped coral bag, 1 muted bronze bag",
"posh turquoise bag contain 3 drab tan bag",
"faded purple bag contain 4 striped fuchsia bag, 3 mirrored fuchsia bag, 2 dotted gray bag, 4 muted coral bag",
"faded bronze bag contain 4 striped bronze bag",
"mirrored lime bag contain 1 muted lavender bag",
"posh gold bag contain 1 mirrored purple bag",
"posh maroon bag contain 1 striped beige bag, 1 wavy red bag, 1 wavy tan bag",
"clear beige bag contain 5 posh turquoise bag, 4 drab tan bag, 2 striped olive bag, 3 plaid olive bag",
"dim purple bag contain 1 striped lime bag",
"vibrant olive bag contain 2 muted yellow bag, 2 plaid aqua bag, 3 dark silver bag, 2 pale green bag",
"bright tan bag contain 5 faded purple bag, 3 dotted gray bag",
"vibrant tomato bag contain 2 pale salmon bag, 2 drab teal bag",
"plaid red bag contain 4 vibrant white bag, 1 posh tan bag",
"mirrored magenta bag contain 3 wavy blue bag, 1 muted tomato bag, 1 striped salmon bag, 1 shiny red bag",
"drab tomato bag contain 2 wavy violet bag, 5 muted aqua bag",
"shiny magenta bag contain 4 mirrored brown bag",
"dull red bag contain 4 plaid green bag",
"dim aqua bag contain 3 mirrored blue bag, 2 bright indigo bag, 4 shiny coral bag",
"faded gray bag contain 4 light lavender bag, 5 clear lime bag, 5 vibrant violet bag",
"dotted lavender bag contain 4 faded crimson bag",
"dull salmon bag contain 2 light plum bag",
"posh yellow bag contain 2 light yellow bag, 2 dim cyan bag, 1 clear crimson bag, 4 posh lavender bag",
"posh tomato bag contain 4 shiny lime bag, 4 bright turquoise bag, 5 shiny tan bag, 4 bright yellow bag",
"plaid lime bag contain 3 shiny salmon bag, 3 plaid crimson bag",
"dim silver bag contain 2 plaid black bag, 3 dull bronze bag, 3 shiny red bag",
"dotted magenta bag contain 3 dotted coral bag, 3 striped blue bag, 3 vibrant tan bag, 3 plaid brown bag",
"muted teal bag contain 3 pale maroon bag",
"vibrant silver bag contain 3 drab lime bag, 1 light aqua bag",
"clear lime bag contain 5 dark plum bag, 3 dotted gray bag",
"dull aqua bag contain 3 posh black bag",
"dark plum bag contain no other bag",
"drab yellow bag contain 4 muted beige bag, 3 clear brown bag, 5 light crimson bag, 5 wavy lavender bag",
"mirrored fuchsia bag contain no other bag",
"posh green bag contain 5 shiny brown bag",
"striped violet bag contain 1 shiny lime bag, 4 pale magenta bag",
"bright turquoise bag contain 1 mirrored lime bag, 1 clear gold bag, 1 muted plum bag",
"dotted beige bag contain 5 plaid aqua bag, 5 muted tomato bag, 5 striped orange bag",
"pale red bag contain 3 striped white bag, 2 drab olive bag, 2 drab black bag, 4 pale chartreuse bag",
"plaid coral bag contain 1 dark beige bag, 2 wavy beige bag, 5 vibrant crimson bag",
"muted indigo bag contain 1 plaid brown bag, 5 striped crimson bag, 5 dotted gray bag, 2 clear maroon bag",
"drab crimson bag contain 1 dim olive bag, 4 drab maroon bag, 3 shiny indigo bag",
"dotted turquoise bag contain 1 light bronze bag",
"vibrant lime bag contain 2 dim lime bag, 5 posh green bag",
"plaid olive bag contain 4 clear black bag",
"pale coral bag contain 3 faded coral bag, 1 posh black bag, 5 faded purple bag, 4 plaid white bag",
"pale cyan bag contain 1 light crimson bag, 1 mirrored blue bag, 4 faded aqua bag",
"plaid salmon bag contain no other bag",
"dim teal bag contain 1 dull white bag",
"bright green bag contain 3 posh beige bag",
"striped red bag contain 2 dotted purple bag",
"plaid silver bag contain no other bag",
"pale fuchsia bag contain 4 mirrored black bag, 5 faded purple bag, 4 plaid violet bag, 3 muted maroon bag",
"pale lime bag contain 2 mirrored bronze bag, 3 clear magenta bag, 4 clear silver bag, 5 plaid indigo bag",
"wavy brown bag contain 3 shiny coral bag, 2 plaid silver bag",
"dark turquoise bag contain 5 drab teal bag, 5 drab gray bag",
"drab coral bag contain 4 shiny coral bag, 1 dull turquoise bag, 1 dotted green bag, 1 light maroon bag",
"posh blue bag contain 4 light blue bag, 2 bright black bag",
"dull lime bag contain 3 faded olive bag, 1 plaid teal bag, 1 shiny lime bag",
"mirrored olive bag contain 1 mirrored beige bag, 3 faded purple bag",
"dim salmon bag contain 5 pale yellow bag, 5 plaid teal bag, 1 posh gray bag",
"clear chartreuse bag contain 2 mirrored fuchsia bag, 5 vibrant magenta bag, 1 dark orange bag",
"vibrant lavender bag contain 5 bright fuchsia bag",
"posh olive bag contain 3 dark olive bag, 2 dotted black bag, 2 clear white bag, 5 dim orange bag",
"pale tan bag contain 5 dull violet bag, 5 vibrant white bag, 2 bright indigo bag, 4 vibrant orange bag",
"dim turquoise bag contain 3 faded purple bag",
"faded fuchsia bag contain 2 clear teal bag",
"posh gray bag contain 4 dotted purple bag, 4 dotted green bag, 5 shiny yellow bag, 1 shiny tan bag",
"posh black bag contain 4 plaid silver bag, 4 vibrant magenta bag, 2 plaid white bag, 4 striped beige bag",
"vibrant gray bag contain 3 light magenta bag",
"dotted purple bag contain 1 plaid salmon bag, 2 bright indigo bag",
"mirrored red bag contain 3 bright tan bag",
"mirrored violet bag contain 5 dark cyan bag",
"faded plum bag contain 4 light violet bag, 3 posh brown bag, 5 dull silver bag, 5 wavy blue bag",
"striped yellow bag contain 3 clear bronze bag",
"striped lime bag contain 2 dark aqua bag, 1 clear lime bag, 2 drab chartreuse bag, 3 clear teal bag",
"clear green bag contain 4 drab magenta bag, 3 dim coral bag",
"bright coral bag contain 4 plaid tomato bag",
"light black bag contain 4 faded coral bag",
"plaid plum bag contain 1 posh violet bag",
"pale gold bag contain 3 clear salmon bag",
"dim tomato bag contain 3 dim indigo bag, 3 dotted turquoise bag",
"bright teal bag contain 4 pale cyan bag",
"striped gold bag contain 1 faded turquoise bag, 1 posh indigo bag, 1 bright black bag",
"pale chartreuse bag contain 1 vibrant magenta bag, 5 dull fuchsia bag, 2 bright gold bag, 4 mirrored blue bag",
"posh tan bag contain 5 light violet bag, 4 drab plum bag",
"pale white bag contain 3 dim blue bag, 4 pale aqua bag, 2 vibrant plum bag",
"dark cyan bag contain 2 shiny teal bag, 3 faded purple bag, 4 shiny indigo bag, 1 striped cyan bag",
"muted turquoise bag contain 4 wavy white bag, 2 dim black bag",
"dull orange bag contain 5 bright teal bag, 3 striped teal bag",
"light aqua bag contain 1 dotted green bag, 4 faded lavender bag, 3 striped green bag",
"clear tan bag contain 3 dim white bag",
"dull maroon bag contain 3 shiny gold bag, 2 light gold bag, 1 dotted orange bag, 1 clear lime bag",
"muted tan bag contain 5 dotted bronze bag, 2 shiny crimson bag",
"dotted indigo bag contain 2 drab beige bag, 5 dotted purple bag, 5 muted maroon bag",
"striped tan bag contain 4 muted chartreuse bag",
"mirrored purple bag contain 3 muted indigo bag",
"faded tomato bag contain 4 dull gold bag, 1 pale tan bag",
"mirrored beige bag contain 1 dark chartreuse bag, 3 dim olive bag",
"pale brown bag contain 4 dull blue bag, 2 plaid tomato bag",
"light green bag contain 3 wavy purple bag, 2 faded purple bag, 4 drab plum bag, 3 shiny yellow bag",
"dark coral bag contain 2 vibrant plum bag, 4 plaid salmon bag",
"dull bronze bag contain 1 dim cyan bag, 2 posh lavender bag, 3 mirrored beige bag",
"faded orange bag contain 2 faded crimson bag",
"mirrored white bag contain 4 wavy crimson bag, 4 pale coral bag, 3 posh silver bag",
"dark maroon bag contain 2 posh teal bag, 4 shiny plum bag",
"drab red bag contain 5 clear red bag, 2 posh magenta bag, 2 vibrant olive bag, 5 mirrored white bag",
"shiny green bag contain 2 mirrored beige bag, 2 wavy tomato bag, 5 striped lavender bag, 1 dim silver bag",
"wavy indigo bag contain 4 dotted white bag",
"dim violet bag contain 5 faded white bag, 3 clear salmon bag",
"striped chartreuse bag contain 3 dim brown bag, 1 mirrored gray bag, 3 clear coral bag, 2 dull aqua bag",
"striped gray bag contain 2 vibrant olive bag, 4 posh beige bag, 3 dull beige bag",
"plaid tomato bag contain 3 clear lime bag",
"dark black bag contain 4 pale crimson bag",
"drab bronze bag contain 5 clear turquoise bag, 4 wavy olive bag, 3 clear purple bag, 4 faded maroon bag",
"dull green bag contain 5 pale fuchsia bag, 3 shiny coral bag, 3 wavy magenta bag",
"faded chartreuse bag contain 2 plaid beige bag, 3 drab orange bag",
"light red bag contain 5 striped lavender bag",
"muted lavender bag contain 2 dark salmon bag, 1 faded indigo bag, 4 clear salmon bag",
"bright white bag contain 1 drab white bag, 3 vibrant purple bag",
"plaid magenta bag contain 5 posh coral bag, 4 plaid indigo bag, 1 plaid violet bag, 1 bright beige bag",
"faded olive bag contain 2 wavy aqua bag",
"posh cyan bag contain 5 shiny coral bag, 5 bright indigo bag, 2 plaid silver bag",
"clear red bag contain 5 dull bronze bag, 4 shiny coral bag, 2 dotted orange bag, 1 vibrant magenta bag",
"bright bronze bag contain 4 dull blue bag",
"striped olive bag contain 3 dim lime bag, 3 pale tan bag, 2 wavy gold bag, 5 mirrored brown bag",
"mirrored green bag contain 3 dull maroon bag, 5 faded tan bag, 5 posh tan bag",
"muted aqua bag contain 1 bright coral bag",
"dim gold bag contain 2 dotted salmon bag",
"pale yellow bag contain 2 wavy coral bag",
"bright yellow bag contain 3 striped lavender bag, 4 vibrant white bag, 3 vibrant plum bag, 1 clear purple bag",
"striped magenta bag contain 1 plaid brown bag, 1 dull indigo bag",
"striped maroon bag contain 2 pale chartreuse bag, 4 dim black bag, 2 muted purple bag",
"bright cyan bag contain 4 muted turquoise bag",
"posh magenta bag contain 3 light gray bag, 2 mirrored blue bag, 3 mirrored silver bag, 2 dotted purple bag",
"striped lavender bag contain 4 bright chartreuse bag, 3 muted plum bag",
"drab lime bag contain 4 posh beige bag, 2 dim olive bag, 4 wavy fuchsia bag, 2 shiny aqua bag",
"mirrored indigo bag contain 4 dark olive bag, 3 mirrored violet bag, 4 mirrored lime bag",
"plaid crimson bag contain 5 striped indigo bag, 2 dark plum bag, 5 dotted green bag, 3 clear salmon bag",
"bright red bag contain 1 pale maroon bag",
"dotted yellow bag contain 2 bright chartreuse bag, 1 posh black bag, 4 bright indigo bag, 1 drab blue bag",
"drab green bag contain 5 light olive bag, 4 vibrant coral bag, 3 light magenta bag",
"shiny crimson bag contain 3 bright olive bag, 1 dotted purple bag, 2 posh cyan bag, 3 dim gray bag",
"pale black bag contain 3 dull tan bag, 5 plaid beige bag, 2 dull violet bag",
"clear purple bag contain 5 muted orange bag, 3 dim gray bag, 5 dotted orange bag",
"pale gray bag contain 5 plaid olive bag, 3 drab coral bag, 1 bright cyan bag",
"light lavender bag contain 5 vibrant white bag, 1 drab plum bag, 5 faded indigo bag, 4 shiny gold bag",
"dull beige bag contain 2 dull black bag",
"clear magenta bag contain 5 posh maroon bag",
"muted orange bag contain 2 dull violet bag, 4 striped beige bag, 1 plaid salmon bag, 3 mirrored fuchsia bag",
"wavy gold bag contain 2 drab turquoise bag",
"pale purple bag contain 1 vibrant crimson bag",
"dark silver bag contain 1 dotted orange bag, 3 plaid beige bag, 5 faded white bag",
"clear lavender bag contain 2 pale violet bag, 5 clear yellow bag, 5 striped salmon bag",
"striped salmon bag contain 4 dim crimson bag",
"shiny gold bag contain 3 vibrant orange bag, 3 plaid silver bag",
"light coral bag contain 4 faded tomato bag, 1 dim lime bag, 1 dotted coral bag, 4 dim chartreuse bag",
"mirrored coral bag contain 2 posh purple bag, 1 dull fuchsia bag, 4 faded maroon bag, 2 plaid indigo bag",
"clear aqua bag contain 5 dim gray bag, 1 dull cyan bag, 2 dim black bag",
"clear salmon bag contain 2 posh gray bag, 5 pale maroon bag",
"muted plum bag contain 2 shiny yellow bag, 1 plaid salmon bag, 3 shiny indigo bag, 4 clear lime bag",
"bright gold bag contain 1 dull blue bag, 2 bright indigo bag, 4 muted red bag, 4 clear maroon bag",
"drab brown bag contain 2 dark chartreuse bag",
"plaid turquoise bag contain 4 striped red bag, 2 faded magenta bag, 1 light magenta bag",
"vibrant turquoise bag contain 2 striped yellow bag, 3 plaid fuchsia bag, 2 shiny coral bag, 1 clear yellow bag",
"dull indigo bag contain 1 drab plum bag, 4 dark fuchsia bag, 3 dotted gray bag",
"wavy aqua bag contain 4 dull tan bag, 1 shiny tan bag, 1 striped beige bag",
"mirrored plum bag contain 4 dark fuchsia bag, 5 muted white bag",
"shiny black bag contain 2 light aqua bag",
"mirrored blue bag contain 2 dim green bag, 4 vibrant white bag, 1 faded orange bag",
"plaid chartreuse bag contain 1 clear tomato bag, 4 shiny orange bag",
"dotted red bag contain 3 plaid beige bag",
"wavy red bag contain 1 striped fuchsia bag, 2 plaid brown bag, 1 shiny fuchsia bag, 2 dotted crimson bag",
"muted violet bag contain 4 posh black bag, 5 shiny turquoise bag, 5 shiny yellow bag",
"dotted gray bag contain 5 dull violet bag, 5 dark plum bag, 2 bright indigo bag, 2 wavy bronze bag",
"faded maroon bag contain 4 pale aqua bag, 2 clear tomato bag",
"dark gray bag contain 1 light orange bag, 1 posh brown bag",
"dull gray bag contain 5 faded violet bag, 1 dotted turquoise bag",
"muted maroon bag contain 1 shiny tan bag, 5 light maroon bag, 2 dotted green bag",
"clear turquoise bag contain 2 clear salmon bag, 1 dark cyan bag, 1 striped green bag",
"wavy bronze bag contain no other bag",
"muted magenta bag contain 5 striped coral bag, 4 dim lime bag, 1 posh red bag, 1 plaid blue bag",
"mirrored cyan bag contain 2 posh violet bag, 5 bright olive bag, 3 dotted green bag, 5 drab gold bag",
"wavy blue bag contain 1 dark coral bag, 1 dim olive bag, 4 dim black bag, 5 drab chartreuse bag",
"vibrant cyan bag contain 3 posh maroon bag, 5 dim beige bag, 3 dark blue bag",
"dim chartreuse bag contain 4 dull tan bag, 5 drab magenta bag",
"dark salmon bag contain 5 bright indigo bag, 4 shiny crimson bag, 3 dotted purple bag, 2 dark coral bag",
"plaid brown bag contain 2 dim olive bag",
"wavy yellow bag contain 2 drab plum bag, 3 muted orange bag, 5 pale coral bag",
"vibrant tan bag contain 5 bright bronze bag, 2 shiny lime bag",
"shiny beige bag contain 2 dull green bag",
"drab gold bag contain 5 dotted crimson bag",
"faded teal bag contain 5 dull tan bag, 3 dotted bronze bag, 4 bright indigo bag, 5 posh red bag",
"mirrored gray bag contain 4 muted bronze bag",
"light fuchsia bag contain 5 pale beige bag, 1 vibrant lavender bag",
"clear indigo bag contain 1 dotted fuchsia bag, 3 dull aqua bag, 1 dark chartreuse bag",
"bright purple bag contain 4 wavy orange bag, 4 mirrored violet bag, 4 light turquoise bag",
"pale green bag contain 1 light aqua bag, 3 bright yellow bag",
"dim olive bag contain 5 dotted green bag, 5 dull violet bag",
"light bronze bag contain 1 dark aqua bag",
"vibrant chartreuse bag contain 3 dark salmon bag",
"pale aqua bag contain 5 dotted purple bag, 4 dark plum bag",
"faded black bag contain 5 mirrored fuchsia bag, 5 striped green bag",
"shiny blue bag contain 1 faded gray bag, 5 dotted indigo bag, 4 faded magenta bag",
"muted red bag contain 1 light violet bag, 4 dim cyan bag",
"shiny yellow bag contain 2 light maroon bag, 3 wavy violet bag",
"clear bronze bag contain 1 bright indigo bag, 1 posh lavender bag, 2 dull salmon bag, 4 muted bronze bag",
"vibrant crimson bag contain 5 drab blue bag",
"shiny purple bag contain 1 shiny teal bag"};
        
        
        
        
        
        }
    }
}